name: generate-r-library-files

on:
  workflow_dispatch:
  repository_dispatch:
    types: [test-trigger]

jobs:
  generate_library:
    runs-on: ubuntu-latest
    container:
      image: cloudfoundry/cflinuxfs3

    steps:
      - name: Install dependencies
        run: |
          apt update
          apt install software-properties-common -y
          add-apt-repository ppa:ubuntugis/ubuntugis-unstable
          add-apt-repository ppa:git-core/ppa
          apt-get update
          apt-get -y install libgdal-dev libgeos-dev libproj-dev libudunits2-dev libnlopt-dev

      - name: Check out code
        uses: actions/checkout@v3

      - name: Make lib_generate.sh executable
        run: chmod +x lib_generate.sh

      - name: Create r-lib
        run: mkdir r-lib

      - name: Run lib_generate.sh for each of the files needed
        run: |
          for L in $LIBS
          do
            find / -iname $L 2>/dev/null | xargs -I {} ./lib_generate.sh {}
          done
        env:
          LIBS: libgdal.so.26 libgeos_c.so libgeos-3.8.0.so libnlopt.so.0 libproj.so libudunits2.so.0 proj.db

      - name: Upload files as an Artifact
        uses: actions/upload-artifact@v2
        with:
          name: r-lib
          path: r-lib
          retention-days: 30
